wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1675101128.575683
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.13.9
      8:
      - 1
      - 5
